apiVersion: v1 
kind: Pod 
metadata: 
  name: ctr 
spec: 
  containers: 
  - name: ctr
    stdin: true
    tty: true
    image: ycliuhw/ctr:latest
    command: ["sleep"]
    args: ["infinity"]
    resources: 
      requests: 
        cpu: 10m 
        memory: 256Mi 
    volumeMounts: 
    - mountPath: /var/run 
      name: docker-sock
  volumes: 
  - name: docker-sock 
    hostPath: 
      path: /var/snap/microk8s/common/run/ 
