apiVersion: v1 
kind: Pod 
metadata: 
  name: docker 
spec: 
  containers: 
  - name: docker
    stdin: true
    tty: true
    image: docker:latest
    command: ['docker', 'run', '-p', '80:80', 'httpd:latest'] 
    resources: 
      requests: 
        cpu: 10m 
        memory: 256Mi 
    volumeMounts: 
    - mountPath: /var/run 
      name: docker-sock
  volumes: 
  - name: docker-sock 
    hostPath: 
      path: /var/run
